
// lang
const trans = {
    en: {
        home: "Home",
        breezair: "Breezair",
        climate: "Climate Wizard",
        contact: "Contact Us",
        sec1title1: "Climate Wizard indirect evaporative cooling",
        sec1p: "Temperatures that rival traditional A/C",
        sec1btn: "Explore the range",
        sec2t1: "Indirect Evaporative Cooling",
        sec2p1: "Climate Wizard indirect evaporative cooling technology",
        sec2p: "uses ahyper- efficient heat exchanger to produce 100% fresh,cool, outside air, with no added moisture.",
        sec2p2: "The fresh cold air produced by indirect evaporative coolers can be similar to that produced by refrigeratedsystems,with temperatures that approach the ambient dew- point temperature, using up to 80% less energy.",
        sec2p3: "No matter how hot it gets outside, indirect evaporative coolers use the same amount of power andstilldelivers 100%fresh, cool air inside.This is in direct contrast to refrigerated systems, which require increasing amountsofpower asoutside temperatures rise.",
        sec2p4: "Indirect evaporative cooling is for ideal in pre-cooling application, stand-alone or supplementary cooling.Indirectevaporative coolers cover an exceptionally large range of flexible configurations in a wide range ofindustries.",
        sec2t2: "Climate Wizard patent",
        sec2p5: "Climate Wizard is a world first and the innovation revolution of the century in cooling technology, using a new way of cooling to deliver unparalleled cooling levels at a fraction of the cost of refrigerated air conditioning. This proven technology has now been successfully adopted across the world.",
        sec2p6: " Climate Wizard uses a patented heat exchanger core separating the airflow where evaporation occurs (working air)and the airflow that is delivered into the building(supply air).This way the supply air can be cooled below the  wet- bulb and contains no moisture.",
        sec2p7: "Let’s have a look at Climate Wizard technology more in details:",
        sec2l1: "How Does It Work?",
        sec2l2: "Explore the benefits",
        sec2l3: "Energy-Saving cooling",
        sec2l4: "Application configurations",
        sec3t1: "Climate Wizard range",
        sec1title: "Dramatically reduces energy consumption and cooling costs, compared to equivalent refrigerated system",
        sec4t1: "How does Climate Wizard indirect evaporative cooling work?",
        sec4p1: "Indirect evaporative air conditioners use a hyper-efficient patented heat exchanger to produce 100% fresh,cool, outside air, with no added moisture.The core is an air- to - air heat exchanger consisting of alternating dry and wet channels",
        sec4p2: "Hot outside air enters the cooler and the fan drives the fresh air through the dry channels.",
        sec4p3: "On exiting, some of the air flows into the building and the remainder is forced back through the wet channels.",
        sec4p4: "Air passing through the wet channels is cooled by water evaporation and cools the channel surface,before being exhausted as warm, moist air.",
        sec4p5: "The temperature of the fresh air passing through the adjacent dry channels is reduced and this cooled air is then transferred into the building without any added moisture.",
        sec5t1: "Climate Wizard control suite",
        sec5p1: "Seeley International has designed the most advanced technology to give you full control of your coolers in the smartest way.",
        sec5p2: "All Climate Wizard H-series and CW-80 coolers can be controlled with the advanced Multi Magic controller suite,including:",
        sec5p3: "Multi Magic touchscreen controllerBMS interface embed in the electronic control module",
        sec5p4: "BMS interface embed in the electronic control module",
        sec5p5: "External temperature sensor",
        sec5p6: "Remote indoor temperature sensor",
        sec5p7: "Climate Wizard CW3 can be controlled with the MagIQtouch suite of controllers, which includes:",
        sec5p8: "MagIQcool thermostat controller",
        sec5p9: "MagIQtouch touchscreen controller",
        sec5p10: "Remote indoor temperature sensor",
        sec5p11: "External temperature sensor",
        sec5p12: "Wi-fi module, which allows coolers to be controlled from the intuitive MagIQtouch app, available both in Apple and Play store",
        sec5p13: "Link module: to link multiple coolers and coolers with other appliances",
        sec5p14: "BMS module",
        sec5btn: "Climate Wizard control suite",
        sec6t1: "Key benefits of Climate Wizard Indirect Evaporative Coolers",
        sec7t1: "Comfortable Indoor Air Quality",
        sec7p1: "Improved IAQ (Indoor Air Quality) with 100% fresh, cool outside air never recirculating stale and recycled air. Temperatures are similar to those produced by refrigerated systems, not adding any moisture to the air.",
        sec7t2: "Reduced Energy use",
        sec7p2: "No high electrical demand charges even in hot weather. Reduce the energy use and improve the cooling performance of existing refrigerated systems(when installed in pre- cooling or supplementary cooling).Total cooling performance increases when air temperature rises.",
        sec8t1: "Flexible applications",
        sec8p1: "Covers an exceptionally large range of flexible configurations (pre-cooling, stand-alone or supplemetary cooling) in a wide range of applications, from light commercial to big industrial plants.",
        sec8t2: "Supporting Sustainability",
        sec8p2:"No synthetic refrigerants are used to cool the air, only water used. Climate Wizard used an exclusive WaterManagement system that helps minimising water consumption.",
        sec9t1: "Climate Wizard Energy-Saving cooling solutions",
        sec10t1: "Hyper-efficient",
        sec10p1: "Climate Wizard’s cooling performance can rival that of refrigerated systems, using up to 80% less energy.That’s not only great for reducing power bills; it’s also great for the environment.And, no matter how hot it gets outside, Climate Wizard uses the same amount of power and still delivers 100% fresh, cool air inside.This is in direct contrast to refrigerated systems, which require increasing amounts of power aoutsidtemperaturerise.Climate Wizard’s cost- saving capabilities actually increase, when the heat is at its highest.At the same time, Climate Wizard’s performance also increases as temperatures rise – again, in complete contrast to refrigerated systems.",
        sec11t1: "Reduced greenhouse gas emissions",
        sec11p1: "Evaporative cooling uses water to cool. This helps reduce the production of greenhouse gases, including harmful hydroflourocarbons.We have estimated that in a location like Madrid(Spain) using Climate Wizard you can reduce running costs up to 82% 1 and carbon emissions up to 89% 2.",
        sec12t1: "Minimal water usage",
        sec12p1: "The technologically advanced water management system continuously checks the quality of the water in your cooler. The system automatically replaces the water when mineral deposits exceed an acceptable level.The optimal result: minimum water use for maximum, fresh cooling power.Furthermore, you can generate your own cooling medium by rain water harvesting and to create a water neutral solution, you can use the waste water for grey, fire or irrigation.",
        sec13t1: "Climate Wizard Applications and Configurations",
        s14: "A WIDE RANGE OF APPLICATIONS FOR CLIMATE WIZARD EVAPORATIVE COOLERS In cases where buildings have reverse cycle air conditioning systems installed, air is recirculated within the indoor space.Drawing fresh air from outside, Indirect Evaporative Cooling(IEC) units are healthier than traditional air conditioning units, by filtering the incoming air, removing most airborne dust and pollen particles and delivering 100% fresh, cool, outside air.Indirect evaporative cooling cuts energy costs, preserve products, customer and staff wellbeing, and provides the required amount of fresh, healthy air at precise temperatures and humidity necessary for the space. Cooling with traditional air conditioning can be challenging and extremely expensive for big areas.Indirect evaporative cooling can be the right solution because it cools large buildings at a fraction of the cost compared to traditional reverse cycle systems.Therefore it makes sense to employ Indirect Evaporative Cooling, a hyper- efficient air conditioning system.This will create a satisfactory environment for workers to maximise productivity whilst at the same time minimising energy costs.",
        s15: "In cases where buildings have reverse cycle air conditioning systems installed, air is recirculated within the indoor space. Drawing fresh air from outside, Indirect Evaporative Cooling(IEC) units are healthier than traditional air conditioning units, by filtering the incoming air, removing most airborne dust and pollen particles and delivering 100% fresh, cool, outside air. Indirect evaporative cooling cuts energy costs, preserve products, customer and staff wellbeing, an provide th required amount of fresh, healthy air at precise temperatures and humidity necessary for the space. Cooling with traditional air conditioning can be challenging and extremely expensive for big areas.Indirect evaporative cooling can be the right solution because it cools large buildings at a fraction of the cost compared to traditional reverse cycle systems.Therefore it makes sense to employ Indirect Evaporative Cooling, a hyper- efficient air conditioning system.This will create a satisfactory environment for workers to maximise productivity whilst at the same time minimising energy costs.",
        s16: "This is why Climate Wizard Indirect Evaporative Cooling units are perfectly suitable for a wide range of applications,including: ",
        s17: "Industrial Plants",
        s18: "Data Centers",
        s19: "Retail and Supermarkets",
        s20: "Schools and offices",
        s21: "Warehouses",
        s22: "Health and aged care facilities",
        s23: "Check all the projects we have done with Climate Wizard:",
        s24: "See all projects",
        s25: "Different configurations for Climate Wizard units",
        s26: "Supported by a team of experienced design consultants and engineers, Climate Wizard Indirect Evaporative Cooling covers an exceptionally large range of flexible configurations in a wide range of industries.",
        s27: "Stand alone cooling",
        s28: "Climate Wizard can be installed in stand alone configuration, when fresh air is needed directly into the space and no other cooling system is previously installed.This way, we directly take advantage of Indoor Air Quality improvement for staff & customers.",
        s29: "Pre-cooling",
        s30: "Indirect evaporative cooling can be retro-fitted to existing reverse cycle VRF installations to pre- cool outside air in any workspace or commercial application, providing fresh cool air to reduce the cooling load on an air handling unit already installed.Acting like an ‘efficiency turbo charger’ the savings are immediate. The key is to hyper- efficiently pre-cool air before it enters the refrigerated air conditioning system.Compressors don’t need to struggle in extreme summer conditions when fed with pre‑cooled air from Climate Wizard. This significantly reduces the load on the system’s energy - hungry compressors.",
        s31: "Supplementary cooling",
        s32: "You can significantly reduce the load on compressors & extends the compressor’s life, even when installation makes it diffucult to install Climate Wizard in pre- cooling(or when unit’s physical layout does not allow direct connection with our indirect evaporative cooler). Climate Wizard can be installed in a convenient location, in parallel with a chiller for example. Climate Wizard provides fresh outside air, while the chiller continues cooling the air inside the building, actually pre- cooled by Climate Wizard.",
        s33: "[1] Seeley International’s running costs comparison is a calculation based on assumptions including Building dimensions 1000m2floor area x 6m high; Cooling time 12hrs / day, 6 summer months/ year; Indoor temperature 22°C; Building heat load 100W / m²; Rooftop Unit - Fresh air 1, 170 l / sec(20 %); Rooftop Unit - COP 3; External ambient conditions based on Typical Meteorological Years(TMY) for Madrid(Spain); Power cost 0.11 €/kWh; Water cost 1.5 €/m³; Electricity Generation CO2equivalent 340gCO2eq / kWh.The comparison should be used as a general guide only.",
        s34: "[2] Seeley International’s running costs comparison is a calculation based on assumptions including Building dimensions 1000m2floor area x 6m high; Cooling time 12hrs / day, 6 summer months/ year; Indoor temperature 22°C; Building heat load 100W / m²; Rooftop Unit - Fresh air 1, 170 l / sec(20 %); Rooftop Unit - COP 3; External ambient conditions based on Typical Meteorological Years(TMY) for Madrid(Spain); Power cost 0.11 €/kWh; Water cost 1.5 €/m³; Electricity Generation CO2equivalent 340gCO2eq / kWh.The comparison should be used as a general guide only.",
        s35: "[3] For more information you can also visit these websites of the organizations mentioned in the article: Rehva ASHRAE WHO",
        s36: "World leading climate control solutions Seeley International is Australia’s largest air conditioning manufacturer and a global leader in developing ingenious, energy- efficient cooling and heating products.",
        s37: "Imam Saud bin Abdulaziz bin Muhammad Road, Riyadh 11514",
        s40: "Pages",
    },
    ar: {
        home: "الرئيسية",
        breezair: "Breezair",
        climate: "Climate Wizard",
        contact: "تواصل معنا",
        sec1title1: "معالج المناخ التبريد التبخيري غير المباشر",
        sec1p: "درجات حرارة تنافس أجهزة التكييف التقليدية",
        sec1btn: "استكشف النطاق",
        sec2t1: "التبريد التبخيري غير المباشر",
        sec2p1: "تقنية التبريد بالتبخير غير المباشر لمعالج المناخ",
        sec2p: "يستخدم مبادل حراري عالي الكفاءة لإنتاج هواء خارجي منعش وبارد بنسبة 100%، بدون رطوبة إضافية.",
        sec2p2: "يمكن أن يكون الهواء البارد النقي الذي تنتجه المبردات التبخيرية غير المباشرة مشابهًا للهواء الذي تنتجه أنظمة التبريد، مع درجات حرارة تقترب من درجة حرارة نقطة الندى المحيطة، باستخدام طاقة أقل بنسبة تصل إلى 80٪.",
        sec2p3: "بغض النظر عن مدى سخونة الجو في الخارج، تستخدم المبردات التبخيرية غير المباشرة نفس القدر من الطاقة ولا تزال توفر هواءًا نقيًا وباردًا بنسبة 100% في الداخل. وهذا يتناقض بشكل مباشر مع أنظمة التبريد، التي تتطلب كميات متزايدة من الطاقة مع ارتفاع درجات الحرارة الخارجية.",
        sec2p4: "يعد التبريد التبخيري غير المباشر مثاليًا في تطبيقات التبريد المسبق، أو التبريد المستقل أو التكميلي. وتغطي المبردات التبخيرية غير المباشرة نطاقًا كبيرًا بشكل استثنائي من التكوينات المرنة في نطاق واسع من الصناعات.",
        sec2t2: "براءة اختراع معالج المناخ",
        sec2p5: "يعتبر برنامج Climate Wizard هو الأول من نوعه في العالم وثورة الابتكار في القرن في مجال تكنولوجيا التبريد، وذلك باستخدام طريقة جديدة للتبريد لتوفير مستويات تبريد لا مثيل لها بجزء صغير من تكلفة تكييف الهواء المبرد. وقد تم الآن اعتماد هذه التكنولوجيا المثبتة بنجاح في جميع أنحاء العالم.",
        sec2p6: "يستخدم برنامج Climate Wizard قلب مبادل حراري حاصل على براءة اختراع يفصل تدفق الهواء حيث يحدث التبخر (الهواء العامل) وتدفق الهواء الذي يتم توصيله إلى المبنى (هواء الإمداد). وبهذه الطريقة يمكن تبريد هواء الإمداد أسفل اللمبة الرطبة ولا يحتوي على رطوبة.",
        sec2p7: "دعونا نلقي نظرة على تقنية معالج المناخ بمزيد من التفاصيل:",
        sec2l1: "كيف يعمل؟",
        sec2l2: "اكتشف الفوائد",
        sec2l3: "التبريد الموفر للطاقة",
        sec2l4: "تكوينات التطبيق",
        sec3t1: "نطاق معالج المناخ",
        sec1title: "يقلل بشكل كبير من استهلاك الطاقة وتكاليف التبريد، مقارنة بنظام التبريد المكافئ",
        sec4t1: "كيف يعمل معالج المناخ التبريد التبخيري غير المباشر؟",
        sec4p1: "تستخدم مكيفات الهواء التبخيرية غير المباشرة مبادلًا حراريًا عالي الكفاءة حاصل على براءة اختراع لإنتاج هواء خارجي بارد ومنعش بنسبة 100%، بدون رطوبة إضافية. القلب عبارة عن مبادل حراري هواء إلى هواء يتكون من قنوات جافة ورطبة متناوبة",
        sec4p2: "يدخل الهواء الخارجي الساخن إلى المبرد وتقوم المروحة بدفع الهواء النقي عبر القنوات الجافة.",
        sec4p3: "عند الخروج، يتدفق بعض الهواء إلى داخل المبنى ويتم إرجاع الباقي عبر القنوات الرطبة.",
        sec4p4: "يتم تبريد الهواء الذي يمر عبر القنوات الرطبة عن طريق تبخر الماء ويبرد سطح القناة، قبل أن يتم استنفاده على شكل هواء دافئ ورطب.",
        sec4p5: "تنخفض درجة حرارة الهواء النقي الذي يمر عبر القنوات الجافة المجاورة، ثم يتم نقل هذا الهواء المبرد إلى المبنى دون أي رطوبة إضافية.",
        sec5t1: "مجموعة التحكم في معالج المناخ",
        sec5p1: "صممت شركة Seeley International التكنولوجيا الأكثر تقدمًا لتمنحك التحكم الكامل في مبرداتك بأذكى طريقة.",
        sec5p2: "يمكن التحكم في جميع مبردات Climate Wizard H-series وCW-80 باستخدام مجموعة وحدات التحكم Multi Magic المتقدمة، بما في ذلك:",
        sec5p3: "وحدة تحكم متعددة اللمس تعمل باللمس. يتم تضمين واجهة BMS في وحدة التحكم الإلكترونية",
        sec5p4: "يتم تضمين واجهة BMS في وحدة التحكم الإلكترونية",
        sec5p5: "مستشعر درجة الحرارة الخارجية",
        sec5p6: " جهاز استشعار درجة الحرارة في الأماكن المغلقة عن بعد",
        sec5p7: "يمكن التحكم في Climate Wizard CW3 باستخدام مجموعة وحدات التحكم MagIQtouch، والتي تتضمن:",
        sec5p8: "جهاز التحكم في درجة الحرارة MagIQcool",
        sec5p9: "وحدة تحكم تعمل باللمس MagIQtouch",
        sec5p10: "جهاز استشعار درجة الحرارة في الأماكن المغلقة عن بعد",
        sec5p11: "مستشعر درجة الحرارة الخارجية",
        sec5p12: "وحدة Wi-fi، التي تسمح بالتحكم في المبردات من خلال تطبيق MagIQtouch البديهي، والمتوفر في متجر Apple وPlay",
        sec5p13: "وحدة الارتباط: لربط مبردات ومبردات متعددة مع الأجهزة الأخرى",
        sec5p14: "وحدة إدارة المباني",
        sec5btn: "مجموعة التحكم في معالج المناخ",
        sec6t1: "الفوائد الرئيسية للمبردات التبخرية غير المباشرة لمعالج المناخ",
        sec7t1: "جودة هواء داخلية مريحة",
        sec7p1: "تحسين جودة الهواء الداخلي (IAQ) مع هواء خارجي بارد ومنعش بنسبة 100% لا يعيد تدوير الهواء القديم أو المعاد تدويره. درجات الحرارة مماثلة لتلك التي تنتجها أنظمة التبريد، ولا تضيف أي رطوبة إلى الهواء.",
        sec7t2: "انخفاض استخدام الطاقة",
        sec7p2: "لا يوجد ارتفاع في رسوم الطلب على الكهرباء حتى في الطقس الحار. تقليل استخدام الطاقة وتحسين أداء التبريد لأنظمة التبريد الحالية (عند تركيبها في التبريد المسبق أو التبريد الإضافي). ويزداد أداء التبريد الإجمالي عندما ترتفع درجة حرارة الهواء.",
        sec8t1: "تطبيقات مرنة",
        sec8p1: "يغطي مجموعة كبيرة بشكل استثنائي من التكوينات المرنة (التبريد المسبق، أو التبريد المستقل، أو التبريد التكميلي) في مجموعة واسعة من التطبيقات، بدءًا من المنشآت التجارية الخفيفة وحتى المنشآت الصناعية الكبيرة.",
        sec8t2: "دعم الاستدامة",
        sec8p2: "لا يتم استخدام أي مبردات صناعية لتبريد الهواء، بل يتم استخدام الماء فقط. استخدم برنامج Climate Wizard نظامًا حصريًا لإدارة المياه يساعد على تقليل استهلاك المياه.",
        sec9t1: "حلول التبريد الموفرة للطاقة لمعالج المناخ",
        sec10t1: "فرط الكفاءة",
        sec10p1: "يمكن لأداء التبريد الخاص ببرنامج Climate Wizard أن ينافس أداء أنظمة التبريد، باستخدام طاقة أقل بنسبة تصل إلى 80%. وهذا ليس رائعًا لتقليل فواتير الطاقة فحسب؛ كما أنه رائع للبيئة. وبغض النظر عن درجة حرارة الجو في الخارج، يستخدم برنامج Climate Wizard نفس القدر من الطاقة ويظل يوفر هواءًا نقيًا وباردًا بنسبة 100% في الداخل. وهذا يتناقض بشكل مباشر مع أنظمة التبريد، التي تتطلب كميات متزايدة من ترتفع الطاقة خارج درجة الحرارة. تزيد بالفعل قدرات برنامج المناخ ويزارد على توفير التكاليف، عندما تكون الحرارة في أعلى مستوياتها. وفي الوقت نفسه، يزداد أداء برنامج المناخ ويزارد أيضًا مع ارتفاع درجات الحرارة - مرة أخرى، على النقيض تمامًا من أنظمة التبريد.",
        sec11t1: "تقليل انبعاثات الغازات الدفيئة",
        sec11p1: "يستخدم التبريد التبخيري الماء للتبريد. ويساعد ذلك على تقليل إنتاج الغازات الدفيئة، بما في ذلك مركبات الهيدروفلوروكربون الضارة. لقد قدرنا أنه في موقع مثل مدريد (إسبانيا) باستخدام Climate Wizard، يمكنك تقليل تكاليف التشغيل بنسبة تصل إلى 82% 1 وانبعاثات الكربون بنسبة تصل إلى 89% 2.",
        sec12t1: "الحد الأدنى من استخدام المياه",
        sec12p1: "يقوم نظام إدارة المياه المتقدم تقنيًا بفحص جودة المياه في المبرد الخاص بك بشكل مستمر. يقوم النظام تلقائيًا باستبدال الماء عندما تتجاوز الرواسب المعدنية مستوى مقبول. النتيجة المثالية: الحد الأدنى من استخدام المياه للحصول على أقصى قدر من طاقة التبريد الطازجة. علاوة على ذلك، يمكنك توليد وسط التبريد الخاص بك عن طريق تجميع مياه الأمطار وإنشاء حل محايد للمياه، يمكنك يمكن استخدام مياه الصرف الصحي للرمادي أو النار أو الري.",
        sec13t1: "تطبيقات وتكوينات معالج المناخ",
        s14: "مجموعة واسعة من التطبيقات للمبردات التبخيرية الخاصة بمعالجة المناخ في الحالات التي تحتوي فيها المباني على أنظمة تكييف هواء ذات دورة عكسية، تتم إعادة تدوير الهواء داخل المساحة الداخلية. ومن خلال سحب الهواء النقي من الخارج، تعد وحدات التبريد التبخيري غير المباشر (IEC) أكثر صحة من وحدات تكييف الهواء التقليدية ، عن طريق تصفية الهواء الوارد، وإزالة معظم جزيئات الغبار وحبوب اللقاح المحمولة بالهواء وتوفير هواء خارجي منعش وبارد بنسبة 100%. ويقلل التبريد بالتبخير غير المباشر من تكاليف الطاقة، ويحافظ على المنتجات، ورفاهية العملاء والموظفين، ويوفر الكمية المطلوبة من الهواء النقي والصحي عند درجات الحرارة والرطوبة الدقيقة اللازمة للمساحة. يمكن أن يكون التبريد باستخدام تكييف الهواء التقليدي أمرًا صعبًا ومكلفًا للغاية بالنسبة للمناطق الكبيرة. يمكن أن يكون التبريد بالتبخير غير المباشر هو الحل الصحيح لأنه يبرد المباني الكبيرة بجزء بسيط من التكلفة مقارنة بأنظمة الدورة العكسية التقليدية. ولذلك فمن المنطقي استخدام التبريد التبخيري غير المباشر ، نظام تكييف هواء عالي الكفاءة. وهذا سيخلق بيئة مرضية للعمال لزيادة الإنتاجية إلى الحد الأقصى مع تقليل تكاليف الطاقة في نفس الوقت.",
        s15: "في الحالات التي يتم فيها تركيب أنظمة تكييف الهواء ذات الدورة العكسية في المباني، تتم إعادة تدوير الهواء داخل المساحة الداخلية. تسحب وحدات التبريد بالتبخير غير المباشر (IEC) الهواء النقي من الخارج، وهي أكثر صحة من وحدات تكييف الهواء التقليدية، وذلك عن طريق تصفية الهواء الوارد وإزالة معظم جزيئات الغبار وحبوب اللقاح المحمولة بالهواء وتوفير هواء خارجي منعش وبارد بنسبة 100%. يعمل التبريد التبخيري غير المباشر على خفض تكاليف الطاقة، والحفاظ على المنتجات، ورفاهية العملاء والموظفين، وتوفير الكمية المطلوبة من الهواء النقي والصحي في درجات حرارة ورطوبة دقيقة ضرورية للمساحة. يمكن أن يكون التبريد باستخدام تكييف الهواء التقليدي أمرًا صعبًا ومكلفًا للغاية بالنسبة للمناطق الكبيرة. يمكن أن يكون التبريد بالتبخير غير المباشر هو الحل الصحيح لأنه يبرد المباني الكبيرة بجزء بسيط من التكلفة مقارنة بأنظمة الدورة العكسية التقليدية. ولذلك فمن المنطقي استخدام التبريد التبخيري غير المباشر ، نظام تكييف هواء عالي الكفاءة. وهذا سيخلق بيئة مرضية للعمال لزيادة الإنتاجية إلى الحد الأقصى مع تقليل تكاليف الطاقة في نفس الوقت.",
        s16: "وهذا هو السبب في أن وحدات التبريد بالتبخير غير المباشر الخاصة بـ Climate Wizard مناسبة تمامًا لمجموعة واسعة من التطبيقات، بما في ذلك:",
        s17: "المنشآت الصناعية",
        s18: "مراكز البيانات",
        s19: "البيع بالتجزئة ومحلات السوبر ماركت",
        s20: "المدارس والمكاتب",
        s21: "المستودعات",
        s22: "المرافق الصحية ورعاية المسنين",
        s23: "تحقق من جميع المشاريع التي قمنا بها باستخدام معالج المناخ:",
        s24: "شاهد جميع المشاريع",
        s25: "تكوينات مختلفة لوحدات معالج المناخ",
        s26: "بدعم من فريق من مستشاري التصميم والمهندسين ذوي الخبرة، يغطي التبريد التبخيري غير المباشر لـ Climate Wizard نطاقًا كبيرًا بشكل استثنائي من التكوينات المرنة في مجموعة واسعة من الصناعات.",
        s27: "تبريد مستقل",
        s28: "يمكن تثبيت Climate Wizard في تكوين مستقل، عندما تكون هناك حاجة إلى هواء نقي مباشرة في المكان ولا يتم تركيب أي نظام تبريد آخر مسبقًا. وبهذه الطريقة، نستفيد بشكل مباشر من تحسين جودة الهواء الداخلي للموظفين والعملاء.",
        s29: "التبريد المسبق",
        s30: "يمكن تركيب التبريد التبخيري غير المباشر بشكل رجعي على تركيبات VRF ذات الدورة العكسية الحالية للتبريد المسبق للهواء الخارجي في أي مساحة عمل أو تطبيق تجاري، مما يوفر هواء باردًا منعشًا لتقليل حمل التبريد على وحدة معالجة الهواء المثبتة بالفعل. الشاحن'التوفير فوري.المفتاح هو التبريد المسبق للهواء بكفاءة عالية قبل أن يدخل إلى نظام تكييف الهواء المبرد.لا تحتاج الضواغط إلى المعاناة في ظروف الصيف القاسية عند تغذيتها بالهواء المبرد مسبقًا من Climate Wizard.وهذا يقلل بشكل كبير من الحمل على طاقة النظام - الضواغط الجائعة.",
        s31: "التبريد التكميلي",
        s32: "يمكنك تقليل الحمل على الضواغط بشكل كبير وإطالة عمر الضاغط، حتى عندما يجعل التثبيت من الصعب تثبيت Climate Wizard في التبريد المسبق (أو عندما لا يسمح التصميم المادي للوحدة بالاتصال المباشر مع المبرد التبخيري غير المباشر الخاص بنا). يمكن تركيب معالج المناخ في مكان مناسب، بالتوازي مع المبرد على سبيل المثال. يوفر برنامج Climate Wizard هواءًا خارجيًا نقيًا، بينما يستمر المبرد في تبريد الهواء داخل المبنى، ويتم تبريده مسبقًا بواسطة Climate Wizard.",
        s33: "[1] مقارنة تكاليف التشغيل لشركة Seeley International عبارة عن حساب يعتمد على افتراضات بما في ذلك أبعاد المبنى 1000 م2 مساحة الأرضية × 6 م الارتفاع؛ وقت التبريد 12 ساعة / يوم، 6 أشهر صيف / سنة؛ درجة الحرارة الداخلية 22 درجة مئوية؛ الحمل الحراري للمبنى 100 وات / م²؛ وحدة السطح - هواء نقي 1، 170 لتر/ثانية(20%)؛ وحدة السطح - COP 3؛ الظروف المحيطة الخارجية بناءً على سنوات الأرصاد الجوية النموذجية (TMY) لمدريد (إسبانيا)؛ تكلفة الطاقة 0.11 يورو/كيلوواط ساعة؛ تكلفة المياه 1.5 يورو/م3؛ توليد الكهرباء مكافئ ثاني أكسيد الكربون 340 جم من مكافئ ثاني أكسيد الكربون / كيلووات ساعة. يجب استخدام المقارنة كدليل عام فقط.",
        s34: "[2] مقارنة تكاليف التشغيل لشركة Seeley International عبارة عن حساب يعتمد على افتراضات بما في ذلك أبعاد المبنى 1000 م2 مساحة الأرضية × 6 م الارتفاع؛ وقت التبريد 12 ساعة / يوم، 6 أشهر صيف / سنة؛ درجة الحرارة الداخلية 22 درجة مئوية؛ الحمل الحراري للمبنى 100 وات / م²؛ وحدة السطح - هواء نقي 1، 170 لتر/ثانية(20%)؛ وحدة السطح - COP 3؛ الظروف المحيطة الخارجية بناءً على سنوات الأرصاد الجوية النموذجية (TMY) لمدريد (إسبانيا)؛ تكلفة الطاقة 0.11 يورو/كيلوواط ساعة؛ تكلفة المياه 1.5 يورو/م3؛ توليد الكهرباء مكافئ ثاني أكسيد الكربون 340 جم من مكافئ ثاني أكسيد الكربون / كيلووات ساعة. يجب استخدام المقارنة كدليل عام فقط.",
        s35: "[3] لمزيد من المعلومات يمكنك أيضًا زيارة هذه المواقع الإلكترونية للمنظمات المذكورة في المقال: Rehva ASHRAE WHO",
        s36: "حلول التحكم في المناخ الرائدة عالميًا، شركة Seeley International هي أكبر شركة مصنعة لأجهزة تكييف الهواء في أستراليا ورائدة عالميًا في تطوير منتجات التبريد والتدفئة المبتكرة والموفرة للطاقة.",
        s37: "طريق الامام سعود بن عبد العزيز بن محمد، الرياض 11514",
        s40: "الصفحات",
    }
}

const lanBtn = document.querySelectorAll('.lang-btn');
const ar = document.getElementById('arBtn');
const en = document.getElementById('enBtn');
lanBtn.forEach(i => i.addEventListener('click', function (e) {

    console.log(i.value);
    if (i.value == "ar") {
        ar.style.display = "none";
        en.style.display = "block";
    } else {
        ar.style.display = "block";
        en.style.display = "none";
    }
    setLang(i.value)
}))

function setLang(lang) {
    const eles = document.querySelectorAll('[data-il8n]');
    eles.forEach(ele => {
        const keys = ele.getAttribute("data-il8n");
        ele.textContent = trans[lang][keys];
    })
}